---
title: "GRE24 23S rRNA phytoplankton taxonomic classes"
author: "Antonia Klatt"
date: "2026-05-27"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

#Load packages

library(readr)
library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)
library(reshape2)
library(patchwork)
library(caret)
library(vegan)
library(dplyr)
library(rioja)
library(ggdendro)
library(stringr)
library(tidyr)

#import data 

#23S rRNA amplicon sequenceing variants (ASV) data (sedDNA)

#ASV count data

Swiss_Lakes_ASV_count <- read.delim(here("Microbiota_Data", "05_OUTPUT","COUNT_phytoplankton.tab"))

#ASV taxonomy data (NCBI)

Swiss_Lakes_ASV_tax <- read.delim(here("Microbiota_Data", "05_OUTPUT","TAXA_phytoplankton.tab"))


#extract ASV counts from Greifensee

#taxonomic phylum level

GRE_ASV_count.a <- str_detect(names(Swiss_Lakes_ASV_count), "GRE24")

GRE_ASV_count <- Swiss_Lakes_ASV_count[, GRE_ASV_count.a]

#taxonomic class level

GRE_ASV_count$class <- Swiss_Lakes_ASV_tax$class

#re-order dataframe to have samples in the right order

#get colnames

colnames(GRE_ASV_count)
#[1] "GRE24SC.02DNA10.12" "GRE24SC.02DNA12.14" "GRE24SC.02DNA16.18" "GRE24SC.02DNA18.20" "GRE24SC.02DNA2.4"  
#[6] "GRE24SC.02DNA20.22" "GRE24SC.02DNA22.24" "GRE24SC.02DNA28.30" "GRE24SC.02DNA30.32" "GRE24SC.02DNA34.36"
#[11] "GRE24SC.02DNA38.40" "GRE24SC.02DNA4.6"   "GRE24SC.02DNA50.52" "GRE24SC.02DNA6.8"   "GRE24SC.02DNA60.62"
#[16] "GRE24SC.02DNA8.10"  "phylum"    

GRE_ASV_count_ord <- rev(GRE_ASV_count[,c(5,12,14,16,1,2,3,4,6,7,8,9,10,11,13,15,17)])

#sum rows with same phylum  

GRE_ASV_count_class <- aggregate(.~class,GRE_ASV_count_ord,FUN=sum)

colnames(GRE_ASV_count_class) <- c("class", rev(c("2012", "2005", "1999", "1993", "1987", "1981", "1970",
                                                  "1963", "1955", "1948", "1928", "1918", "1898", "1878",
                                                  "1818", "1768")))

#The age model is based on varve counting down to 24 cm (we sliced up the cores in three - year intervals). 
#Below that, the ages are based on the age model from McKenzie and Hollander, 1993, and are assumed to be 5 years/cm. 
#These samples integrate 2 cm and represent ~ 10 years of accumulation, as opposed to 3 years per sample in the upper part of the core.

```

## Stratigraphically constrained clustering (CONISS) of 23S rRNA data

```{r}

#create dissimilarity matrix based on Bray Curtis distance (like in NDMS)

GRE.a <- GRE_ASV_count_class[,-1]

rownames(GRE.a) <-GRE_ASV_count_class$class

GRE_ASV_class_for_CONISS <- as.data.frame(t(GRE.a))

#remove all columns with rowSums = 0

GRE_ASV_class_for_CONISS.1 <- GRE_ASV_class_for_CONISS[, apply(GRE_ASV_class_for_CONISS[1:(ncol(GRE_ASV_class_for_CONISS))], 2, sum)!=0]

GRE24_ASV_dist <- vegdist(GRE_ASV_class_for_CONISS.1, method="bray", binary=FALSE, diag=FALSE, upper=FALSE)


#CONISS constrained cluster analysis chclust(d, method = "coniss")

GRE24_ASV_CONISS <-chclust(GRE24_ASV_dist, method = "coniss")

plot(GRE24_ASV_CONISS, cex.axis=0.5, cex= 0.75, main= "CONISS GRE24 ASV")

bstick(GRE24_ASV_CONISS, ng=10, plot=TRUE, title = "Broken stick model CONISS GRE24 ASV") 
#cluster 2 is significant

#extract dendrogram

GRE24_ASV_dendro <- as.dendrogram(GRE24_ASV_CONISS)

GRE24_ASV_dend_data <- dendro_data(GRE24_ASV_dendro)

#replace labels (order) in dendrogram by actual ages with approxfun for aligning plots

#Code adapted from https://stackoverflow.com/questions/65207033/how-do-i-plot-dendrogram-leaves-by-a-given-value-depth-in-a-sediment-core-rath (accessed 22.07.2025)

dendAge <- approxfun(GRE24_ASV_dend_data$labels$x, as.numeric(as.character(GRE24_ASV_dend_data$labels$label))) 
GRE24_ASV_dend_data$segments$x <- dendAge(GRE24_ASV_dend_data$segments$x)
GRE24_ASV_dend_data$segments$xend <- dendAge(GRE24_ASV_dend_data$segments$xend)

pGRE24_ASV_CONISS <- ggplot(segment(GRE24_ASV_dend_data)) +
  ggtitle(expression('CONISS'['23S rRNA ASVs']), subtitle="CONISS")+
  scale_x_continuous(limits=c(1768,2012))+
  annotate("rect", xmin =  1950 ,xmax = 1980 ,ymin = -Inf, ymax = Inf, alpha=0.065, fill="red1")+ 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) +
  scale_y_continuous()+
  theme_dendro()+
  theme( plot.title = element_text(size=35, hjust=0.5),
         plot.subtitle = element_blank(),
         plot.margin = unit(c(1,0.5,0,0.5), "cm"))

#plotting relative abundances of algal taxononomic classes

#before plotting: summarize low abundant classes for plotting with colSums < 10% 

GRE_ASV_count_class.a <- GRE_ASV_count_class[,2:17]
row.names(GRE_ASV_count_class.a) <- GRE_ASV_count_class$class


#remove all rows with colSums <20

GRE_ASV_class_red1 <- GRE_ASV_count_class.a[apply(GRE_ASV_count_class.a, 1, sum) >= 20, ]

GRE_ASV_class_red2.a <- GRE_ASV_count_class.a[apply(GRE_ASV_count_class.a, 1, sum) <= 20, ]

#GRE_ASV_class_red2.b <- GRE_ASV_count_class.a[apply(GRE_ASV_count_class.a, 1, sum) == 0, ] #sum to 0
#GRE_ASV_class_red2.b 

#Glaucocystophyceae     
#Mamiellophyceae        
#Prasinodermophyceae    
#Xanthophyceae 

GRE_ASV_count_class.b2 <- as.data.frame(t(GRE_ASV_class_red1))

GRE_ASV_count_class.b2$year <- as.numeric(row.names(GRE_ASV_count_class.b2))


GRE_ASV_count_class2 <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Bangiophyceae',
                                                                                      'Chlorophyceae', 
                                                                                      'Cyanophyceae', 
                                                                                      'Euglenida',
                                                                                      'Eustigmatophyceae',
                                                                                      'Trebouxiophyceae'))


GRE_Cyano <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Cyanophyceae'))

pCyano <- ggplot()+
  geom_area(data=GRE_Cyano, aes(x = year, y = value, fill=variable),
            alpha=0.75, color='darkslategray') +
  scale_fill_manual(labels= c(Cyanophyceae='Cyanophyceae'),
                    values= c(Cyanophyceae= 'darkslategray'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='right',limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012))+
  xlab(expression(atop("","Year CE"))) +  ylab(expression(italic(Cyanophyceae)~'(%)'))+  
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = 'darkslategray'), 
        axis.ticks = element_line(colour = 'darkslategray'), 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=35,color='darkslategray'),
        axis.line.x =element_blank(),
        axis.text.y = element_text(size=35,color='darkslategray'),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position= "none",
        plot.margin = unit(c(0,0.5,-5,0.5), "cm"))



GRE_Chloro <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Chlorophyceae'))

pChloro <- ggplot()+
  geom_area(data=GRE_Chloro, aes(x = year, y = value, fill=variable),
            alpha=0.75, color='aquamarine4') +
  scale_fill_manual(labels= c(Chlorophyceae= 'Chlorophyceae'),
                    values= c(Chlorophyceae= 'aquamarine4'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='left',limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012))+
  xlab(expression(atop("","Year CE"))) +  ylab(expression(italic(Chlorophyceae)~'(%)'))+  
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = 'aquamarine4'), 
        axis.ticks = element_line(colour = 'aquamarine4'),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=35,color='aquamarine4'),
        axis.line.x =element_blank(),
        axis.text.y = element_text(size=35,color='aquamarine4'),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position= "none",
        plot.margin = unit(c(-5,0.5,-5,0.5), "cm"))


GRE_Treboux <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Trebouxiophyceae'))

pTreboux <- ggplot()+
  #annotate("rect", xmin =  1950 ,xmax = 1980 ,ymin = -Inf, ymax = Inf, alpha=0.065, fill="red1")+ 
  geom_area(data=GRE_Treboux, aes(x = year, y = value, fill=variable),
            alpha=0.75, color='#9ACAD0') +
  scale_fill_manual(labels= c(Trebouxiophyceae= 'Trebouxiophyceae'),
                    values= c(Trebouxiophyceae= '#9ACAD0'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='right',limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012))+
  xlab(expression(atop("","Year CE"))) +  ylab(expression(italic(Trebouxiophyceae)~'(%)'))+   
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = '#9ACAD0'), 
        axis.ticks = element_line(colour = '#9ACAD0'), 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=35,color='#9ACAD0'),
        axis.line.x =element_blank(),
        axis.text.y = element_text(size=35,color='#9ACAD0'),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position= "none",
        plot.margin = unit(c(-5,0.5,-5,0.5), "cm"))


GRE_Euglenida <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Euglenida'))

pEuglenida <- ggplot()+
  geom_area(data=GRE_Euglenida, aes(x = year, y = value, fill=variable),
            alpha=0.75, color='tan') +
  scale_fill_manual(labels= c(Euglenida= 'Euglenida'),
                    values= c(Euglenida = 'tan'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='left',limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012))+
  xlab(expression(atop("","Year CE"))) +  ylab('Euglenida (%)')+   
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = 'tan'), 
        axis.ticks = element_line(colour = 'tan'), 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=35,color='tan'),
        axis.line.x =element_blank(),
        axis.text.y = element_text(size=35,color='tan'),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position= "none",
        plot.margin = unit(c(-5,0.5,-5,0.5), "cm"))


GRE_Eustig <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Eustigmatophyceae'))

pEustig <- ggplot()+
  geom_area(data=GRE_Eustig, aes(x = year, y = value, fill=variable),
            alpha=0.75, color='tan3') +
  scale_fill_manual(labels= c(Eustigmatophyceae= 'Eustigmatophyceae'),
                    values= c(Eustigmatophyceae= 'tan3'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='right',limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012))+
  xlab(expression(atop("","Year CE"))) +  ylab(expression(italic(Eustigmatophyceae)~'(%)'))+   
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = 'tan3'),
        axis.ticks = element_line(colour = 'tan3'),
        #legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=35,color='tan3'),
        axis.line.x =element_blank(),
        axis.text.y = element_text(size=35,color='tan3'),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        #legend.position=c(0.175, -0.05),
        legend.position= "none",
        plot.margin = unit(c(-5,0.5,-5,0.5), "cm"))


GRE_Bangio <- melt(GRE_ASV_count_class.b2, id.vars="year", measure.vars = c('Bangiophyceae'))

pBangio <- ggplot()+
  geom_area(data=GRE_Bangio, aes(x = year, y = value, fill=variable),
            alpha=0.5, color='red4') +
  scale_fill_manual(labels= c(Bangiophyceae= 'Bangiophyceae'),
                    values= c(Bangiophyceae= 'red4'),
                    name= '23S rRNA ASV')+
  scale_y_continuous(position='left', limits=c(0,105), expand=c(0,0))+
  scale_x_continuous(limits=c(1768,2012), breaks=c(1770,1790,1810,1830,1850,1870,1890,1910,1930,1950,1970,1990,2010))+
  xlab(expression(atop("","Year CE"))) +  ylab(expression(italic(Bangiophyceae)~'(%)'))+   
  theme(panel.background = element_rect(fill = NA, color = NA),
        plot.background  = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.y = element_line(colour = 'red4'),
        axis.ticks.y = element_line(colour = 'red4'),
        axis.line.x = element_line(colour = 'black'),
        axis.ticks.x = element_line(colour = 'black'),
        axis.text.x = element_text(size=35,color="black", angle=45, vjust=0.5),
        axis.text.y = element_text(size=35,color="red4"),
        axis.title.x = element_text(size=35,color="black"),
        axis.title.y = element_text(size=35,color="red4"),
        legend.position= "none",
        plot.margin = unit(c(-5,0.5,0.5,0.5), "cm"))


Fig3 <- plot_grid(pGRE24_ASV_CONISS, pCyano, pChloro, pTreboux, pEuglenida, pEustig, pBangio,
          nrow=7, rel_heights = c(0.5,1.475, 1,1,1,1, 2), axis= "rl", align= "v")


```

# Fig. 3

```{r, fig.width = 15, fig.height = 32.5, echo=FALSE}

plot(Fig3)

```
